/**:
  ros__parameters:
    video_device: "/dev/video0"
    image_width: 1920
    image_height: 1080
    framerate: 30.0
    pixel_format: "mjpeg2rgb"
    camera_name: "obsbot_tiny_2_lite"
    camera_info_url: "package://construction_robot_perception/config/obsbot_tiny_2_lite.yaml"
    frame_id: "default_cam"
    io_method: "mmap"
